routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('auth', 'Auth\SsoController@handleProviderCallback');
Route::post('logout', 'Auth\SsoController@logout')->name('logout');

Route::redirect('/', '/links');

Route::group(['middleware' => 'auth'], function(){
    Route::resource('links', 'LinkController');
    Route::resource('gateways', 'GatewayController');

    Route::get('transactions', 'TransactionController@index')->name('transactions.index');
    Route::get('transactions/export', 'TransactionController@export')->name('transactions.export');

    Route::get('links/{link}/export', 'LinkController@export')->name('links.export');
    Route::get('links/{link}/products/export', 'LinkController@exportProducts')->name('links.products.export');
    Route::get('links/{link}/dashboard', 'LinkController@dashboard')->name('links.dashboard');

    Route::get('/products/{product}/pick', 'ProductController@pick')->name('product.pick');

    Route::get('/transactions/{transaction}/status/toggle','TransactionStatusController')->name('transactions.status.toggle');
});

Route::group(['middleware' => ['web','isCustomer']], function(){
    // public link to start a transaction
    Route::get('{link}', 'TransactionController@create')->name('transaction.create');
    Route::post('{link}', 'TransactionController@store')->name('transaction.store');
    Route::get('{link}/history', 'TransactionController@history')->name('transaction.history');

    // payment page for stripe payments
    Route::get('pay/{transaction}', 'PaymentController@create')->name('payment.create');
    Route::post('pay/{transaction}', 'PaymentController@charge')->name('payment.charge');
});


// error link
Route::get('t/{transaction}/error', 'TransactionController@error')->name('transaction.error');
// after payment return link
Route::get('t/{transaction}','TransactionController@show')->name('payment-return-url');

// webhook
Route::post('t/{provider}','TransactionController@update')->name('webhook-url');

app/Link.php
<?php

namespace App;

use App\Enums\LinkExpireType;
use App\Enums\TransactionStatus;
use App\Gateway;
use App\Product;
use App\Scopes\TenantScope;
use App\Tenant;
use App\Transaction;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Link extends Model
{
    use SoftDeletes;

    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope(new TenantScope);
    }

    public $casts = [
        'with_tip' => 'boolean',
        'with_tickets' => 'boolean',
        'show_status' => 'boolean',
    ];

    public function getRouteKeyName()
    {
        return 'code';
    }

    public function scopeActive(Builder $query){
        return $query
            ->where('expire_type', new LinkExpireType(LinkExpireType::Never))
            ->orWhere(function($query){
                $query->where([
                    ['expire_type','=', new LinkExpireType(LinkExpireType::ByDate)],
                    ['expiration_date','>',Carbon::now()]
                ]);
            });
    }

    public function scopeExpired(Builder $query){
        return $query->where('expire_type', new LinkExpireType(LinkExpireType::ByDate))
            ->where('expiration_date','<',Carbon::now());
    }

    public function isExpired(): bool
    {
        if($this->expire_type == 'never') return false;
        if(Carbon::create($this->expiration_date)->isFuture()) return false;
        return true;
    }

    public function tenant()
    {
        return $this->belongsTo(Tenant::class);
    }

    public function gateways()
    {
        return $this->belongsToMany(Gateway::class);
    }

    public function transactions()
    {
        return $this->hasMany(Transaction::class)->orderBy('updated_at','DESC');
    }
    
    public function products()
    {
        return $this->hasMany(Product::class);
    }

    public function hasProducts(): bool
    {
        return $this->products->count() > 0;
    }

    public function hasTips() : bool
    {
        return $this->with_tip;
    }

    public function getProductSalesAttribute()
    {
        $this->transactions()->paid()
            ->join('transactions_products','transactions.id','=','transactions_products.transaction_id')
            ->sum('transactions_products.cost');

//        return $this->transactions()->transactions()->paid()->sum('cost');
    }

    public function feeMultiplier()
    {
        return $this->fee / 100;
    }

    public function getRaisedAttribute(): string
    {
        return number_format($this->transactions()->paid()->sum('transactions.amount'),2);
    }

    public function paidCustomers()
    {
        return $this->transactions()->paid()->groupBy('transactions.customer_id');
    }

    public function raisedForGateway(Gateway $gateway): string
    {
        return number_format($this->transactions()->paid()->forGateway($gateway->id)->sum('transactions.amount'),2,'.',',');
    }
    
    public function raisedForProduct(Product $product): string
    {
        return number_format($this->products()->where('id',$product->id)->transactions()->paid()->sum('transactions.amount'),2,'.',',');
    }

    public function raisedForProducts(): string
    {
        return number_format($this->transactions()->paid()
            ->join('transaction_products','transactions.id','=','transaction_products.transaction_id')
            ->sum('transaction_products.cost'), 2,'.',',');
    }

    public function raisedDonations(): string
    {
        $product_transactions =  $this->transactions()->paid()
            ->join('transaction_products','transactions.id','=','transaction_products.transaction_id')
            ->sum('transaction_products.cost');

        $total = $this->transactions()->paid()->sum('transactions.amount');

        return number_format($total - $product_transactions,2,'.',',');
    }


    public function participantsForGateway(Gateway $gateway){
        return $this->transactions()->forGateway($gateway->id)->paid()->distinct('transactions.customer_id');
    }

    public function transactionsForGateway(Gateway $gateway){
        return $this->transactions()->forGateway($gateway->id)->paid();
    }
}

app/Product.php
<?php

namespace App;

use App\Transaction;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

/**
 * @property mixed $remainingTickets
 */
class Product extends Model
{
    public function transactions()
    {
        return $this->belongsToMany(
            Transaction::class, 
            'transaction_products',
            'product_id',
            'transaction_id',
        )->withPivot('amount','cost');
    }

    public function hasLimitedAvailability(): bool
    {
        return $this->availability_limit > 0;
    }

    public function getRemainingTicketsAttribute()
    {
        return max($this->availability_limit - $this->tickets(),0);
    }

    public function isAvailable(): bool
    {
        if(!$this->hasLimitedAvailability()) {
            return true;
        }

        return $this->remainingTickets > 0;
    }

    public function count()
    {
        return $this->transactions()->paid()->sum('transaction_products.cost');
    }

    public function scopeForLink(Builder $query, $id)
    {
        return $query->where('link_id', $id);
    }

    public function link()
    {
        return $this->belongsTo(Link::class);
    }

    public function tickets()
    {
        return $this->transactions()->paid()->sum('transaction_products.amount');
    }
    
    public function raised()
    {
        return number_format($this->count(),2,'.',',');
    }
}

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Customer;
use App\Enums\GatewayType;
use App\Enums\LinkDescriptionType;
use App\Enums\LinkPriceType;
use App\Enums\TransactionStatus;
use App\Http\Requests\StoreTransaction;
use App\Link;
use App\Payments\MolliePayment;
use App\Payments\SquarePayment;
use App\Payments\StripePayment;
use App\Transaction;
use Exception;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Validation\ValidationException;
use Spatie\SimpleExcel\SimpleExcelWriter;

class TransactionController extends Controller
{
    private function getTransactions($range) : Builder
    {
        $transactions = Transaction::with('link','customer')
            ->paid()
            ->notEmpty()
            ->orderBy('created_at', 'desc');

        $start = now()->timezone('America/Los_Angeles')->startOfDay();
        $end = now()->timezone('America/Los_Angeles')->endOfDay();

        switch ($range){
            case 'year':
                $transactions->forRange($start->startOfYear(), $end->endOfYear());
                break;
            case 'last_year':
                $transactions->forRange($start->subYear()->startOfYear(), $end->subYear()->endOfYear());
                break;
            case 'quarter':
                $transactions->forRange($start->startOfQuarter(), $end->endOfQuarter());
                break;
            case 'last_quarter':
                $transactions->forRange($start->subQuarter()->startOfQuarter(), $end->subQuarter()->endOfQuarter());
                break;
            case 'month':
                $transactions->forRange($start->startOfMonth(), $end->endOfMonth());
                break;
            case 'last_month':
                $transactions->forRange($start->subMonth()->startOfMonth(), $end->subMonth()->endOfMonth());
                break;
            case 'week':
                $transactions->forRange($start->startOfWeek(), $end->endOfWeek());
                break;
            case 'last_week':
                $transactions->forRange($start->subWeek()->startOfWeek(), $end->subWeek()->endOfWeek());
                break;
            case 'today':
                $transactions->forRange($start, $end);
                break;
            default:
                $transactions->forRange($start->subDays(30), $end);
                break;
        }

        return $transactions;
    }

    public function index()
    {
        $range = request()->input('range', 'l30');

        return view('admin.transactions.index', [
            'transactions' => $this->getTransactions($range)->get(),
            'range' => $range,
            'ranges' => ['l30', 'year','last_year','quarter','last_quarter','month','last_month','week','last_week', 'today'],
        ]);
    }

    public function export(){
        $range = request()->input('range', 'l30');

        $transactions = $this->getTransactions($range)->get();
        $writer = SimpleExcelWriter::streamDownload("Transactions.xlsx");

        $transactions->each(function(Transaction $transaction) use ($writer){
            $writer->addRow([
                'Id' => $transaction->id,
                'PersonId' => $transaction->customer->person_id,
                'Name' => $transaction->customer->name,
                'Link' => $transaction->link->title,
                'Description' => $transaction->description,
                'Amount' => $transaction->amount,
                'Fee' => $transaction->charged_amount,
                'Total' => $transaction->amount + $transaction->charged_amount,
                'Date' => $transaction->created_at->timezone('America/Los_Angeles')->format('m/d/y H:i:s'),
            ]);
        });

       $writer->toBrowser();
    }

    // shown after a payment
    public function show(Request $request, Transaction $transaction){
        $request->session()->flush();

        return view('transactions.show', compact('transaction'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function create(Request $request, Link $link)
    {
        if($link->isExpired()){
            return view('transactions.expired');
        }

        $link->load('gateways');
        $customer = $request->session()->get('customer');

        return view('transactions.form', compact('link','customer'));
    }

    public function history(Request $request, Link $link)
    {
        $customer = $request->session()->get('customer');

        if(!$customer) {
            return "Customer not found";
        }

        $transactions = $customer->transactions()->paid()
            ->forLink($link->id)->with('products')->get();

        return view('transactions.history', compact('link','customer', 'transactions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreTransaction  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(StoreTransaction $request, Link $link)
    {
        $gateways = $link->gateways;
        if($gateways->count() == 1){
            $gateway = $gateways->first();
        }else{
            $gateway = $gateways->find($request->gateway);
        }

        if(is_null($gateway)){
            throw ValidationException::withMessages(['gateway' => "Please select a valid payment method"]);
        }

        if($link->with_tickets && is_null($request->name)){
            throw ValidationException::withMessages(['name' => "Please fill out the name."]);
        }

        $customer = Customer::find($request->session()->get('customer.id'));
        
        if($gateway == null || $customer == null){
            throw ValidationException::withMessages([
                "amount" => ["Something went wrong"], 
            ]);
        }

        // this is a raffle
        if($request->products){

            // look through all products that the link has
            $products = $link->products()->get()->reduce(function($acc, $product) use ($request){
                if($product->multiplier === 0){
                    return $acc;
                }

                // product is not bought
                if(!array_key_exists($product->id, $request->products) || !$request->products[$product->id]){
                    return $acc;
                }

                // product amount is below 1
                if($request->products[$product->id]['amount'] < 1){
                    return $acc;
                }

                // include the multiplier in the sales
                $amount = (int) round($request->products[$product->id]['amount'] * $product->multiplier);

                if ($product->hasLimitedAvailability() && $amount > $product->remainingTickets){
                    throw ValidationException::withMessages([
                        'products.' . $product->id => ["There are only $product->remainingTickets tickets available"],
                    ]);
                }

                $acc[] = [
                    'product_id' => $product->id,
                    'amount' => $amount,
                    'cost' => $amount * $product->price,
                    'multiplier' => $product->multiplier
                ];
                return $acc;
            },[]);

            $amount = collect($products)->sum('cost');
        }else{
            $amount = $link->price_type === LinkPriceType::FIXED() ? $link->price : $request->amount;
            // set products
            $products = null;
        }

        if($link->with_tip && $request->tip > 0){
            $amount+= $request->tip;
        }

        if($amount < 0.50) {
            throw ValidationException::withMessages([
                "amount" => [$request->products ? "Please select at least 1 product" : 'Add an amount'],
            ]);
        }

        $description = ($link->description_type === LinkDescriptionType::FIXED() ? $link->description : $request->input('description'));

        if($description == ""){
            $description = $link->title;
        }

        $transaction = new Transaction();
        $transaction->id = time();
        $transaction->link_id = $link->id;
        $transaction->name = $link->with_tickets ? $request->input('name',null) : $customer->name;
        $transaction->tenant_id = $link->tenant_id;
        $transaction->gateway_id = $gateway->id;
        $transaction->customer_id = $customer->id;
        $transaction->amount = $amount;
        $transaction->charged_amount = $link->fee ? $amount * $link->feeMultiplier() : $amount;
        $transaction->description = $description;
        $transaction->status = TransactionStatus::Open();
        $transaction->save();

        try{
            switch($gateway->type) {
                case GatewayType::Stripe:
                    $payment = new StripePayment($gateway);
                break;
                case GatewayType::Mollie:
                    $payment = new MolliePayment($gateway);
                break;
                case GatewayType::Square:
                    $payment = new SquarePayment($gateway);
                break;
                default:
                    throw new Exception("No payment provider set");
            };
        }catch(\Exception $e){
            Log::info($e);
            return redirect()->route('transaction.error', $transaction);
        }

        $paymentIntend = $payment->create($transaction, $customer);
        $transaction->external_reference = $paymentIntend->id;

        $transaction->save();

        if(!is_null($products)){
            $transaction->products()->attach($products);
        }

        return redirect($paymentIntend->url, 303);
    }

   /**

resources/views/transactions/error.blade.php
@extends('layouts.public')

@section('content')
    <div class="flex items-center mt-24">
        <div class="w-full sm:w-full md:w-1/2 md:mx-auto md:p-0 lg:w-1/2 max-w-2xl">
            <div class="flex flex-col break-words bg-white sm:border sm:border-2 rounded shadow-md p-12">
                <h1 class="text-2xl mb-8 text-center">{{ $link->title }}</h1>
	            
                	<div class="rounded-full mx-auto bg-red-200 w-32 h-32">
		            	<svg class="fill-current text-red-500 w-12 h-12 mt-10 mx-auto" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
	                	<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"></svg>
		            		<path d="M10 8.586L2.929 1.515 1.515 2.929 8.586 10l-7.071 7.071 1.414 1.414L10 11.414l7.071 7.071 1.414-1.414L11.414 10l7.071-7.071-1.414-1.414L10 8.586z"/>
		            	</svg>
		            </div>
                	<p class="w-full text-center text-lg mt-10 text-red-600 leading-loose"><b>Oops</b> The payment could not be made.<br>Try again later</p>
            </div>
        </div>
    </div>
@endsection

resources/views/transactions/form.blade.php
@extends('layouts.public')

@section('content')
    <div class="flex items-center mt-6 sm:mt-16 md:mt-20 lg:mt-24">
        <form class="w-full sm:w-full md:w-2/3 mx-auto md:p-0 lg:w-1/2 max-w-2xl" method="post" action="{{route('transaction.store', $link->code)}}">
            <div class="flex flex-col break-words bg-white sm:border-2 rounded shadow-md p-6 sm:px-12 sm:py-8">
                <h1 class="text-2xl sm:text-3xl md:text-4xl mb-8 text-center leading-normal">{{ $link->title }}</h1>
                @if($link->show_status)
                    <div class="flex flex-wrap xl:flex-no-wrap mb-12">
                        @include('admin.partials.infoblock',['data' => ['Raised' => "$". $link->raised, 'Transactions' => $link->transactions()->paid()->count()]])
                    </div>
                @endif
                <p class="w-full text-xl block mb-8" >Hi <span class="font-bold">{{$customer->name}}</span>, </p>
                @csrf
                @if($link->gateways->count() > 1)
                <div class="mb-6">
                    <span class="font-medium w-full block mb-2">Choose the recipient</span>
                    <div class="border rounded-lg border-gray-300"> 
                        @foreach($link->gateways as $key => $gateway)
                        <label class="px-5 py-4 block overflow-hidden width-full cursor-pointer border-gray-300 border-b last:border-b-0">
                            <input type="radio" class="form-radio block float-left h-8 w-8" name="gateway" value="{{$gateway->id}}" @if(sizeof($link->gateways) == 1) checked="checked" @endif>
                            <span class="ml-4 pt-1 block float-left text-xl">{{ $gateway->name }}</span>
                        </label>
                        @endforeach
                    </div>
                    @error('gateway')<div class="text-red-500 alert alert-danger mt-2">{{ $message }}</div> @enderror
                </div>
                @endif

                @if($link->with_tickets)
                    <div class="mb-4">
                        <span class="font-medium w-full block mb-2">Purchase for</span>
                        <div class="w-full flex relative">
                            <input type="text" name="name" class="p-4 text-2xl text-gray-800 rounded-lg border border-gray-500 block w-full outline-none" placeholder="This can be any name you want" value="{{old('name',$customer->name)}}">
                        </div>
                        @error('name')<div class="text-red-500 alert alert-danger mt-2">{{ $message }}</div> @enderror
                    </div>
                    <div class="mb-10">
                        <a href="{{route('transaction.history',$link)}}" class="text-blue-500 hover:underline text-lg">See your purchases</a>
                    </div>
                @endif

                @if(!$link->hasProducts() )
                    @if($link->price_type == "FIXED")
                        <div class="mb-6" >
                            <span class="font-medium w-full block mb-2">Amount</span>
                            <div class="w-full block relative">
                                <span class="text-4xl text-gray-500 font-mono absolute pt-4 px-5">$</span>
                                <input type="hidden" name="amount" value="{{$link->price}}">
                                <div class="pl-12 py-4 text-4xl text-gray-600 bg-gray-200 font-mono tracking-tighter rounded-lg border block w-full outline-none">{{$link->price}}</div>
                            </div>

                            @error('amount')<div class="text-red-500 alert alert-danger mt-2">{{ $message }}</div> @enderror
                        </div>
                    @else
                        <div class="mb-6">
                            <span class="font-medium w-full block mb-2">Choose your amount</span>
                            <div class="w-full block relative">
                                <span class="text-4xl text-gray-500 font-mono absolute pt-5 px-5">$</span>
                                <input type="text" name="amount" class="pl-12 py-4 text-4xl text-gray-600 font-mono tracking-tighter rounded-lg border block w-full outline-none" value="{{old('amount')}}">
                            </div>

                            @error('amount')<div class="text-red-500 alert alert-danger mt-2">{{ $message }}</div> @enderror
                        </div>
                    @endif
                <div class="mb-6">
                    <span class="font-medium w-full block mb-2">Description</span>
                    @if($link->description_type != "fixed") 
                        <textarea rows="3" name="description" class="px-5 py-4 text-gray-800 text-xl tracking-tight rounded-lg border block w-full outline-none" placeholder="Payment for . . .">{{ old('description',$link->description) }}</textarea>
                    @else
                        <div class="bg-gray-200 px-5 py-4 text-gray-800 text-xl tracking-tight rounded-lg border block w-full outline-none">{{ $link->description }}</div>
                        <div class="text-gray-500 alert alert-danger mt-2">You will see this description on your transaction.</div>
                    @endif
                    @error('description')<div class="text-red-500 alert alert-danger mt-2">{{ $message }}</div> @enderror
                </div>
                @else
                <div class="mb-6">
                    <span class="font-medium w-full block mb-4">Select from following options:</span>
                    @foreach ($link->products as $product )
                        <div class="w-full mb-6">
                            @if(!is_null($product->image))
                            <img alt="image" src="{{$product->image}}"  class="mb-2 mt-10" />
                            @endif
                            <div class="w-full flex relative items-center">
                                <div class="flex w-full flex-wrap">
                                <h2 class="w-full text-xl md:text-2xl break-all py-3">{{$product->name}}
                                    @if($product->hasLimitedAvailability() && $product->isAvailable())
                                        <span class="block leading-normal text-gray-600 text-base">
                                            <b>{{$product->remaining_tickets}}</b> Tickets Remaining
                                        </span>
                                    @endif
                                    @if($product->multiplier > 1)
                                    <span class="block leading-normal text-green-600 text-xl">
                                        <b>&times;{{$product->multiplier}}</b> Ticket Multiplier
                                    </span>
                                    @endif
                                </h2>
                                    <small class="w-full text-gray-600 text-base mb-2">{{$product->description}}</small>
                                </div>
                                @if($product->multiplier > 0)
                                    @if($product->isAvailable())
                                        <div class="flex items-center">
                                            <span class="block w-16 md:w-32 text-right text-lg md:text-2xl text-gray-500 pr-3">${{$product->price}} x</span>
                                            <input oninput="input()" data-amount="{{ $product->price }}"
                                           inputmode="numeric"
                                            type="number"
                                            min="0"
                                            step="1"
                                            max="{{$product->hasLimitedAvailability() ? $product->remainingTickets : ''}}"

                                            @if(!$product->isAvailable())
                                             disabled="disabled"
                                             @endif

                                            name="products[{{$product->id}}][amount]"
                                            placeholder="0"
                                            value="{{old('products.'.$product->id . '.amount')}}"
                                            class="product p-3 text-md sm:text-xl md:text-2xl text-gray-600 font-mono tracking-tighter rounded-lg border block w-16 md:w-24 outline-none border-gray-500">
                                        </div>
                                    @else
                                        <div class="flex items-center">
                                            <span class="block w-32 text-right text-xl md:text-2xl text-red-800">Sold Out</span>
                                        </div>
                                    @endif
                                @endif

                            </div>
                            @error('products.'.$product->id)<div class="text-red-500 alert alert-danger mb-2 text-right">{{ $message }}</div> @enderror
                        </div>


                    @endforeach
                    @error('amount')<div class="text-red-500 alert alert-danger mt-2 text-lg">{{ $message }}</div> @enderror
                </div>
                @endif
                @if($link->with_tip)
                    <div class="mb-12">
                        <span class="font-medium w-full block mb-2">Add a donation</span>
                        <div class="w-full flex relative">
                            <span class="text-4xl text-gray-500 font-mono absolute pt-5 px-5">$</span>
                            <input type="number"  inputmode="decimal" oninput="input()" id="tip" step="0.1" name="tip" class="pl-12 py-4 text-4xl text-gray-600 font-mono tracking-tighter rounded-lg border border-gray-500 block w-full outline-none" value="{{old('tip')}}">
                        </div>
                        @error('tip')<div class="text-red-500 alert alert-danger mt-2">{{ $message }}</div> @enderror
                    </div>
                @endif
                <button type="submit" id="submitButton" class="bg-blue-500 hover:bg-blue-400 border border-blue-600 inline-block py-4 text-3xl text-center rounded text-white">Pay</button>
                @if($link->fee)
                    <div class="text-gray-500 text-base mt-2 text-center">A {{$link->fee}}% transaction fee will be added.</div>
                @endif

                @if(!$link->with_tickets)
                    <div class="mt-12 text-center">
                        <a href="{{route('transaction.history',$link)}}" class="text-blue-500 hover:underline text-lg">See previous payments for {{$link->title}}</a>
                    </div>
                @endif
            </div>
        </form>
    </div>
@endsection

@section('script')
<style >
    #submitButton[disabled=disabled], #submitButton:disabled {
        opacity: 0.2!important;
        cursor: not-allowed;
    }
</style>
<script >
    const submitButton = document.getElementById("submitButton");
    const formatter = new Intl.NumberFormat('us-US', { style: 'currency', currency: 'USD' });

    function input(){
        const products = document.getElementsByClassName('product');
        let total = 0;

        if(!products.length) return;
        
        for(let prod of products){
            const price = Number(prod.dataset.amount);
            const count = Math.round(Number(prod.value));
            if(count < 1) {
                continue;
            }
            const amount = Math.round((price * count) * 100) / 100
            total = Math.round((total + amount) * 100 ) / 100;
        }

        let tip = 0;
        const tipInput = document.getElementById("tip");
        if(tipInput && !isNaN(tipInput.value)){
            const value = Number(tipInput.value);
            if(value> 0){
                tip = value;
            }
        }

        if(total + tip < 0.5){
            submitButton.innerText = "Pay";
            submitButton.disabled = true;
        }else{
            submitButton.innerText = `Pay ${formatter.format(total+ tip)}`;
            submitButton.disabled = false;
        }
    }

    input();

</script>

@endsection

resources/views/transactions/stripe.blade.php
<html>
<head>
    <script src="https://js.stripe.com/v3/"></script>
    <script>
        var stripe = Stripe('{{$transaction->gateway->public_key}}');
        stripe.redirectToCheckout({
            sessionId: "{{$transaction->external_reference}}"
        });
    </script>
</head>
</html>