routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('auth', 'Auth\SsoController@handleProviderCallback');
Route::post('logout', 'Auth\SsoController@logout')->name('logout');

Route::redirect('/', '/links');

Route::group(['middleware' => 'auth'], function(){
    Route::resource('links', 'LinkController');
    Route::resource('gateways', 'GatewayController');

    Route::get('transactions', 'TransactionController@index')->name('transactions.index');
    Route::get('transactions/export', 'TransactionController@export')->name('transactions.export');

    Route::get('links/{link}/export', 'LinkController@export')->name('links.export');
    Route::get('links/{link}/products/export', 'LinkController@exportProducts')->name('links.products.export');
    Route::get('links/{link}/dashboard', 'LinkController@dashboard')->name('links.dashboard');

    Route::get('/products/{product}/pick', 'ProductController@pick')->name('product.pick');

    Route::get('/transactions/{transaction}/status/toggle','TransactionStatusController')->name('transactions.status.toggle');
});

Route::group(['middleware' => ['web','isCustomer']], function(){
    // public link to start a transaction
    Route::get('{link}', 'TransactionController@create')->name('transaction.create');
    Route::post('{link}', 'TransactionController@store')->name('transaction.store');
    Route::get('{link}/history', 'TransactionController@history')->name('transaction.history');

    // payment page for stripe payments
    Route::get('pay/{transaction}', 'PaymentController@create')->name('payment.create');
    Route::post('pay/{transaction}', 'PaymentController@charge')->name('payment.charge');
});


// error link
Route::get('t/{transaction}/error', 'TransactionController@error')->name('transaction.error');
// after payment return link
Route::get('t/{transaction}','TransactionController@show')->name('payment-return-url');

// webhook
Route::post('t/{provider}','TransactionController@update')->name('webhook-url');

app/Gateway.php
<?php

namespace App;

use App\Scopes\TenantScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Gateway extends Model
{
    use SoftDeletes;
    /**
     * The "booting" method of the model.
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot();

        // static::addGlobalScope(new TenantScope);
    }

    public function tenant()
    {
        return $this->belongsTo('App\Tenant');
    }
}

app/Http/Controllers/GatewayController.php
<?php

namespace App\Http\Controllers;

use App\Gateway;
use Illuminate\Http\Request;
use App\Enums\GatewayType;
use \App\Http\Requests\StoreGateway;


class GatewayController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     */
    public function index()
    {
        $gateways = Gateway::orderBy('created_at','DESC')->get();
        return view('admin.gateways.index', compact('gateways'));
    }

    /**
     * Show the form for creating a new resource.
     *
     */
    public function create()
    {
        $types = GatewayType::getValues();
        return view('admin.gateways.form',compact('types'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreGateway  $request
     */
    public function store(StoreGateway $request)
    {
        $gateway =  new Gateway();
        $gateway->name = $request->input('name');
        $gateway->type = $request->input('type');
        $gateway->public_key = $request->input('public_key');
        $gateway->private_key = $request->input('private_key');

        $gateway->save();

        return redirect(route('gateways.index'))->with('status','A new bank account has been created');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Gateway  $gateway
     */
    public function edit(Gateway $gateway)
    {
        $types = GatewayType::getValues();

        return view('admin.gateways.form', compact(['gateway','types']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\StoreGateway  $request
     * @param  \App\Gateway  $gateway
     */
    public function update(StoreGateway $request, Gateway $gateway)
    {
        $gateway->name = $request->input('name');
        $gateway->type = $request->input('type');
        $gateway->public_key = $request->input('public_key');
        $gateway->private_key = $request->input('private_key');

        $gateway->save();

        return redirect(route('gateways.index'))->with('status','The bank account has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Gateway  $gateway
     */
    public function destroy(Gateway $gateway)
    {
        $gateway->delete();

        return redirect(route('gateways.index'))->with('status','The integration has been archived');

    }
}

resources/views/admin/gateways/form.blade.php
@extends('layouts.app')

@section('content')
    <div class="flex items-center">
        <div class="w-full sm:w-full px-4 md:w-3/4 md:mx-auto md:p-0 lg:w-2/3 max-w-5xl">

            @if (session('status'))
                <div class="text-sm border border-t-8 rounded text-green-700 border-green-600 bg-green-100 px-3 py-4 mb-4" role="alert">
                    {{ session('status') }}
                </div>
            @endif

            <div class="flex justify-end justify-between mb-5">
                <h1 class="font-medium text-gray-500 pt-4">
                    @if(isset($gateway))
                        Edit Integration
                    @else
                        Add Integration
                    @endif
                </h1>
            </div>
            <div class="flex flex-col break-words bg-white border border-2 rounded shadow-md">
                <form method="post" action="{{(isset($gateway) ? route('gateways.update', $gateway) : route('gateways.store') )}}" class="px-6 py-10">
                    @if(isset($gateway)) @method('put') @endif
                    @csrf
                    <div class="mb-6">
                        <span class="font-medium w-full block mb-2">Title</span>
                        <input value="@if(isset($gateway)){{$gateway->name}}@endif" class="text-xl border p-2 block w-full rounded bg-gray-100" type="text" name="name" placeholder="What is this integration called?">
                        @error('title')  <div class="text-red-500 alert alert-danger mt-2">{{ $message }}</div> @enderror
                    </div>

                     <div class="mb-6">
                        <span class="font-medium w-full block mb-2">Account type</span>
                        @foreach($types as $type)
                            <label class="inline-flex cursor-pointer block w-full py-2 border-gray-200">
                                <input type="radio" class="form-radio" name="type" value="{{$type}}" @if(isset($gateway) && $gateway->type === $type) checked="checked" @endif>
                                <span class="ml-2">{{$type}}</span>
                            </label>
                        @endforeach
                        @error('type')<div class="text-red-500 alert alert-danger mt-2">{{ $message }}</div> @enderror
                    </div>

                    <div class="mb-6">
                        <span class="font-medium w-full block mb-2">Public Key</span>
                        <textarea class="text-xl border p-2 block w-full rounded bg-gray-100" name="public_key">@if(isset($gateway)){{$gateway->public_key}}@endif</textarea>
                        @error('public_key')  <div class="text-red-500 alert alert-danger mt-2">{{ $message }}</div> @enderror
                    </div> 
                    <div class="mb-12">
                        <span class="font-medium w-full block mb-2">Private Key</span>
                        <textarea class="text-xl border p-2 block w-full rounded bg-gray-100" name="private_key">@if(isset($gateway)){{$gateway->private_key}}@endif</textarea>
                        @error('private_key')  <div class="text-red-500 alert alert-danger mt-2">{{ $message }}</div> @enderror
                    </div>

                   
                    <button class="bg-blue-500 hover:bg-blue-400 text-white border border-blue-600 text-white py-3 px-4 rounded inline-block float-right" type="submit">@if(isset($gateway)) Save @else Create @endif</button>

                    <a href="{{route('gateways.index')}}" class="float-right py-3 mx-4 text-gray-700">Cancel</a>
                </form>
            </div>

            @if(isset($gateway))
                <form method="POST" action="{{route('gateways.destroy',$gateway)}}" class="bg-white w-full border border-2 shadow-md rounded mt-6 px-6 py-10 flex items-center">
                    @csrf
                    @method('DELETE')
                    <p class="text-lg">Archive this Integration</p>
                    <button type="submit" class="ml-auto bg-red-200 hover:bg-red-100 border border-red-400 inline-block py-4 px-5 rounded text-red-800">Delete</button>
                </form>
            @endif
        </div>
    </div>
@endsection

resources/views/admin/gateways/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mx-auto">
        @if (session('status'))
            <div class="text-sm border border-t-8 rounded text-green-700 border-green-600 bg-green-100 px-3 py-4 mb-4" role="alert">
                {{ session('status') }}
            </div>
        @endif

        <div class="w-full block float-left relative">
           <div class="absolute w-full flex justify-between">
                <h1 class="font-medium text-gray-500 pt-4">
                    Integrations
                </h1>
                <a class="bg-blue-500 hover:bg-blue-400 text-white border border-blue-600 inline-block py-4 px-5 rounded" href="{{route('gateways.create')}}">Add Integration</a>
            </div>
            <table class="bg-white border rounded shadow-md py-6 mt-16 w-full">
                <tr class="bg-gray-100 border-b-2">
                    <th class="px-6 py-4 uppercase text-sm text-gray-500 text-left">Name</th>
                    <th class="uppercase text-sm text-gray-500 text-left">Last changed</th>
                    <th class=""></th>
                </tr>

            @foreach($gateways as $gateway)
                <tr class="border-b">
                    <td class="px-6 py-6">{{$gateway->name}}</td>
                    <td class="py-6 font-bold ">{{$gateway->updated_at->diffForHumans()}}</td>
                    <td class="text-right pr-2">
                        <a href="{{route('gateways.edit',$gateway)}}" class="bg-gray-200 hover:bg-gray-100 border border-gray-400 inline-block py-3 px-4 rounded text-gray-800">Edit</a>
                    </td>
                </tr>
            @endforeach
            </table>
        </div>
    </div>
@endsection