routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('auth', 'Auth\SsoController@handleProviderCallback');
Route::post('logout', 'Auth\SsoController@logout')->name('logout');

Route::redirect('/', '/links');

Route::group(['middleware' => 'auth'], function(){
    Route::resource('links', 'LinkController');
    Route::resource('gateways', 'GatewayController');

    Route::get('transactions', 'TransactionController@index')->name('transactions.index');
    Route::get('transactions/export', 'TransactionController@export')->name('transactions.export');

    Route::get('links/{link}/export', 'LinkController@export')->name('links.export');
    Route::get('links/{link}/products/export', 'LinkController@exportProducts')->name('links.products.export');
    Route::get('links/{link}/dashboard', 'LinkController@dashboard')->name('links.dashboard');

    Route::get('/products/{product}/pick', 'ProductController@pick')->name('product.pick');

    Route::get('/transactions/{transaction}/status/toggle','TransactionStatusController')->name('transactions.status.toggle');
});

Route::group(['middleware' => ['web','isCustomer']], function(){
    // public link to start a transaction
    Route::get('{link}', 'TransactionController@create')->name('transaction.create');
    Route::post('{link}', 'TransactionController@store')->name('transaction.store');
    Route::get('{link}/history', 'TransactionController@history')->name('transaction.history');

    // payment page for stripe payments
    Route::get('pay/{transaction}', 'PaymentController@create')->name('payment.create');
    Route::post('pay/{transaction}', 'PaymentController@charge')->name('payment.charge');
});


// error link
Route::get('t/{transaction}/error', 'TransactionController@error')->name('transaction.error');
// after payment return link
Route::get('t/{transaction}','TransactionController@show')->name('payment-return-url');

// webhook
Route::post('t/{provider}','TransactionController@update')->name('webhook-url');

app/Link.php
<?php

namespace App;

use App\Enums\LinkExpireType;
use App\Enums\TransactionStatus;
use App\Gateway;
use App\Product;
use App\Scopes\TenantScope;
use App\Tenant;
use App\Transaction;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Link extends Model
{
    use SoftDeletes;

    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope(new TenantScope);
    }

    public $casts = [
        'with_tip' => 'boolean',
        'with_tickets' => 'boolean',
        'show_status' => 'boolean',
    ];

    public function getRouteKeyName()
    {
        return 'code';
    }

    public function scopeActive(Builder $query){
        return $query
            ->where('expire_type', new LinkExpireType(LinkExpireType::Never))
            ->orWhere(function($query){
                $query->where([
                    ['expire_type','=', new LinkExpireType(LinkExpireType::ByDate)],
                    ['expiration_date','>',Carbon::now()]
                ]);
            });
    }

    public function scopeExpired(Builder $query){
        return $query->where('expire_type', new LinkExpireType(LinkExpireType::ByDate))
            ->where('expiration_date','<',Carbon::now());
    }

    public function isExpired(): bool
    {
        if($this->expire_type == 'never') return false;
        if(Carbon::create($this->expiration_date)->isFuture()) return false;
        return true;
    }

    public function tenant()
    {
        return $this->belongsTo(Tenant::class);
    }

    public function gateways()
    {
        return $this->belongsToMany(Gateway::class);
    }

    public function transactions()
    {
        return $this->hasMany(Transaction::class)->orderBy('updated_at','DESC');
    }
    
    public function products()
    {
        return $this->hasMany(Product::class);
    }

    public function hasProducts(): bool
    {
        return $this->products->count() > 0;
    }

    public function hasTips() : bool
    {
        return $this->with_tip;
    }

    public function getProductSalesAttribute()
    {
        $this->transactions()->paid()
            ->join('transactions_products','transactions.id','=','transactions_products.transaction_id')
            ->sum('transactions_products.cost');

//        return $this->transactions()->transactions()->paid()->sum('cost');
    }

    public function feeMultiplier()
    {
        return $this->fee / 100;
    }

    public function getRaisedAttribute(): string
    {
        return number_format($this->transactions()->paid()->sum('transactions.amount'),2);
    }

    public function paidCustomers()
    {
        return $this->transactions()->paid()->groupBy('transactions.customer_id');
    }

    public function raisedForGateway(Gateway $gateway): string
    {
        return number_format($this->transactions()->paid()->forGateway($gateway->id)->sum('transactions.amount'),2,'.',',');
    }
    
    public function raisedForProduct(Product $product): string
    {
        return number_format($this->products()->where('id',$product->id)->transactions()->paid()->sum('transactions.amount'),2,'.',',');
    }

    public function raisedForProducts(): string
    {
        return number_format($this->transactions()->paid()
            ->join('transaction_products','transactions.id','=','transaction_products.transaction_id')
            ->sum('transaction_products.cost'), 2,'.',',');
    }

    public function raisedDonations(): string
    {
        $product_transactions =  $this->transactions()->paid()
            ->join('transaction_products','transactions.id','=','transaction_products.transaction_id')
            ->sum('transaction_products.cost');

        $total = $this->transactions()->paid()->sum('transactions.amount');

        return number_format($total - $product_transactions,2,'.',',');
    }


    public function participantsForGateway(Gateway $gateway){
        return $this->transactions()->forGateway($gateway->id)->paid()->distinct('transactions.customer_id');
    }

    public function transactionsForGateway(Gateway $gateway){
        return $this->transactions()->forGateway($gateway->id)->paid();
    }
}

app/Http/Controllers/LinkController.php
<?php

namespace App\Http\Controllers;

use App\Customer;
use App\Enums\LinkExpireType;
use App\Enums\LinkPriceType;
use App\Enums\TransactionStatus;
use App\Gateway;
use App\GatewayLink;
use App\Http\Requests\StoreLink;
use App\Link;
use App\Transaction;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Mollie\Laravel\Facades\Mollie;
use Spatie\SimpleExcel\SimpleExcelReader;
use Spatie\SimpleExcel\SimpleExcelWriter;

class LinkController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     */
    public function index(Request $request)
    {
        $links = Link::active()->where('level','<=',$request->user()->level)->orderBy('created_at','DESC')->get();

        return view('admin.links.index', compact('links'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Link  $link
     */
    public function show(Link $link, Request $request)
    {
        return view('admin.links.show',[
            'link' => $link,
            'transactions' => $link->transactions()->paid()->get(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     */
    public function create(Request $request)
    {
        $gateways = Gateway::where('tenant_id', auth()->user()->tenant_id)->get();

        return view('admin.links.form', compact('gateways'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreLink  $request
     */
    public function store(StoreLink $request)
    {

        // create link
        $link = new Link();
        $link->title = $request->title;
        $link->description = $request->description;
        $link->description_type = ($request->description_type == 'fixed' ? "fixed" : 'open');

        $link->price_type = ($request->price_type == 'FIXED' ? LinkPriceType::FIXED() : LinkPriceType::Open());
        $link->price = $request->price;
        $link->with_tip = $request->with_tip;
        $link->with_tickets = $request->with_tickets;

        $link->code = Str::slug($request->title);
        $link->price_type = LinkPriceType::Open();
        $link->expire_type = LinkExpireType::Never();
        $link->fee = $request->fee;

        $link->save();

        $gatewayLinks = [];
        foreach ($request->input('gateways') as $gateway_id) {
            $gatewayLinks[] = [
                'gateway_id' => $gateway_id,
                'link_id' => $link->id,
                'tenant_id' => auth()->user()->tenant_id,
            ];
        }

        // create gateway-link
        GatewayLink::insert($gatewayLinks);

        return redirect(route('links.show',$link))->with('status','A new link is created');

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Link  $link
     */
    public function edit(Link $link)
    {
        $gateways = Gateway::where('tenant_id', auth()->user()->tenant_id)->get();
        
        return view('admin.links.form', compact(['gateways','link']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Link  $link
     */
    public function update(StoreLink $request, Link $link)
    {
        $link->title = $request->input('title', $link->title);
        $link->code = Str::slug($link->title);
        $link->fee = $request->input('fee', $link->fee);
        $link->description = $request->input('description');
        $link->description_type = ($request->input('description_type') == 'fixed' ? "fixed" : 'open');

        $link->price_type = ($request->price_type == 'FIXED' ? LinkPriceType::FIXED() : LinkPriceType::Open());
        $link->price = $request->price;
        $link->with_tip = $request->with_tip;
        $link->with_tickets = $request->with_tickets;
        $link->show_status = $request->show_status;

        $gatewayLinks = [];
        foreach ($request->input('gateways') as $gateway_id) {
            $gatewayLinks[$gateway_id] = [
                'link_id' => $link->id,
                'tenant_id' => auth()->user()->tenant_id,
            ];
        }

        $link->gateways()->sync($gatewayLinks);
        $link->save();

        return redirect(route('links.show',$link))->with('status','The link has been updated');
    }

    public function destroy(Link $link)
    {
        $link->delete();
        return redirect(route('links.index'))->with('status','The link has been deleted');
    }

    public function dashboard(Link $link){
        if($link->hasProducts()){
            return view('admin.links.products',compact('link'));
        }else{
            return view('admin.links.dashboard',compact('link'));
        }
    }

    public function export(Link $link){
        $transactions = $link->transactions()->paid()->with('customer')->get();

        $title = Str::slug($link->title,'_') . "_" . now()->timezone('America/Los_Angeles')->format('m-d-y_H:i:s') . '.xlsx';
        $writer = SimpleExcelWriter::streamDownload($title);
        
        $transactions->each(function($transaction) use ($writer){
            $writer->addRow([
                'id' => $transaction->id,
                'PersonId' => $transaction->customer->person_id,
                'Name' => $transaction->customer->name,
                'Email' => $transaction->customer->email,
                'Description' => $transaction->description,
                'Status' => $transaction->status,
                'Amount' => $transaction->amount,
                'Fee' => $transaction->charged_amount,
                'Created' => $transaction->created_at->timezone('America/Los_Angeles')->format('m/d/y H:i:s'),
            ]);
        });
            
        $writer->toBrowser();
    }
    
    public function exportProducts(Link $link){
        $products = $link->products();
        $title = Str::slug($link->title,'_') . "_PRODUCTS_" . now()->timezone('America/Los_Angeles')->format('m-d-y_H:i:s') . '.xlsx';
        $writer = SimpleExcelWriter::streamDownload($title);
        
        $products->each(function($product) use ($writer){
            $product->transactions()->paid()->each(function($transaction) use ($writer, $product){
                for($i=0;$i<$transaction->pivot->amount;$i++){
                    $writer->addRow([
                        'Name' => $transaction->name,
                        'Product' => $product->name,
                    ]);
                }
            });
        });
            
        $writer->toBrowser();
    }
}

resources/views/admin/links/form.blade.php
@extends('layouts.app')

@section('content')
    <div class="flex items-center">
        <div class="w-full sm:w-full px-4 md:mx-auto md:p-0 max-w-3xl">

            @if (session('status'))
                <div class="text-sm border border-t-8 rounded text-green-700 border-green-600 bg-green-100 px-3 py-4 mb-4" role="alert">
                    {{ session('status') }}
                </div>
            @endif

            <div class="flex justify-between mb-5">
                <h1 class="font-medium text-gray-500 pt-4">
                    @if(isset($link))
                        Edit Link
                    @else
                        Create new Link 
                    @endif
                </h1>
            </div>
            <div class="flex flex-col break-words bg-white border-2 rounded shadow-md">
                <form method="post" action="{{(isset($link) ? route('links.update', $link) : route('links.store') )}}" class="px-6 pt-10 pb-6">
                    @if(isset($link)) @method('put') @endif
                    @csrf
                    <div class="mb-6">
                        <span class="font-medium w-full block mb-2">Title</span>
                        <input value="@if(isset($link)){{$link->title}}@else{{old('title')}}@endif" class="text-xl border p-4 block w-full rounded bg-gray-100" type="text" name="title" placeholder="This link is for ...">
                        @error('title')  <div class="text-red-500 alert alert-danger mt-2">{{ $message }}</div> @enderror
                    </div>

                    <div class="mb-8">
                        <span class="font-medium w-full block mb-2">Description</span>
                        <textarea class="text-xl border p-2 block w-full rounded bg-gray-100" name="description">@if(isset($link)){{$link->description}}@else {{ old('description') }}@endif</textarea>
                        @error('description')  <div class="text-red-500 alert alert-danger mt-2">{{ $message }}</div> @enderror

                        <label class="inline-flex cursor-pointer w-full py-2 border-gray-200">
                            <input type="checkbox" class="form-checkbox" name="description_type" value="fixed" @if(isset($link) && $link->description_type == "fixed") checked="checked" @endif>
                            <span class="ml-2">Show this description on the invoice for every donation.</span>
                        </label>
                    </div>
                    <div class="flex w-full mb-6">
                        <div class="w-full flex">
                            <div class="w-full">
                                <span class="font-medium w-full block mb-2">Price</span>
                                <div class="flex relative w-24">
                                    <select name="price_type" class="p-3 border rounded ">
                                        <option value="Open" @if((isset($link) && $link->price_type == 'Open') || old('price_type') == 'Open') selected @endif">Open</option>
                                        <option value="FIXED" @if((isset($link) && $link->price_type == 'FIXED') || old('price_type') == 'FIXED') selected @endif">Fixed</option>
                                    </select>
                                </div>
                                @error('price_type')  <div class="text-red-500 alert alert-danger mt-2">{{ $message }}</div> @enderror
                            </div>
                            <div class="w-full">
                                <span class="font-medium w-full block mb-2">Price</span>
                                <div class="flex relative w-32">
                                    <span class="text-2xl text-gray-500 font-mono absolute pt-3 px-5 left-0">$</span>
                                    <input value="@if(isset($link)){{$link->price}}@else{{old('price','0')}}@endif" class="pl-10 py-3 text-xl text-gray-600 font-mono tracking-tighter rounded-lg border w-full outline-none text-left" step="0.1" type="number" name="price">
                                </div>
                                @error('description')  <div class="text-red-500 alert alert-danger mt-2">{{ $message }}</div> @enderror
                            </div>
                        </div>

                        <div class="w-full">
                            <span class="font-medium w-full block mb-2">Processing fee</span>
                            <div class="flex relative w-24">
                                <input value="@if(isset($link)){{$link->fee}}@else{{old('fee','3')}}@endif" class="pr-8 pl-3 py-3 text-xl text-gray-600 font-mono tracking-tighter rounded-lg border w-full outline-none text-center" type="number" name="fee">
                                <span class="text-2xl text-gray-500 font-mono absolute pt-3 px-5 right-0">%</span>
                            </div>
                            @error('fee')  <div class="text-red-500 alert alert-danger mt-2">{{ $message }}</div> @enderror
                        </div>

                    </div>
                    <div class="w-1/2 mb-6">
                        <span class="font-medium w-full block mb-2">Options</span>
                        <label class="inline-flex cursor-pointer block w-full py-2 border-gray-200">
                            <input type="checkbox" class="form-checkbox" name="with_tip" value="true" @if(isset($link) && $link->with_tip) checked="checked" @endif>
                            <span class="ml-2">Allow Tipping</span>
                        </label>
                        <label class="inline-flex cursor-pointer block w-full py-2 border-gray-200">
                            <input type="checkbox" class="form-checkbox" name="with_tickets" value="true" @if(isset($link) && $link->with_tickets) checked="checked" @endif>
                            <span class="ml-2">Sell Tickets</span>
                        </label>
                        <label class="inline-flex cursor-pointer block w-full py-2 border-gray-200">
                            <input type="checkbox" class="form-checkbox" name="show_status" value="true" @if(isset($link) && $link->show_status) checked="checked" @endif>
                            <span class="ml-2">Show Status on the link page</span>
                        </label>
                        @error('with_tip')  <div class="text-red-500 alert alert-danger mt-2">{{ $message }}</div> @enderror
                        @error('with_tickets')  <div class="text-red-500 alert alert-danger mt-2">{{ $message }}</div> @enderror
                        @error('show_status')  <div class="text-red-500 alert alert-danger mt-2">{{ $message }}</div> @enderror
                    </div>

                    <div class="mb-6">
                        <span class="font-medium w-full block mb-2">Payment Providers:</span>
                        @foreach($gateways as $gateway)
                            <label class="inline-flex cursor-pointer w-full py-2 border-gray-200">
                                <input type="checkbox" class="form-checkbox" name="gateways[]" value="{{$gateway->id}}" @if(isset($link) && $link->gateways->contains('id',$gateway->id)) checked="checked" @endif>
                                <span class="ml-2">{{$gateway->name}}</span>
                            </label>
                        @endforeach
                        @error('gateways')<div class="text-red-500 alert alert-danger mt-2">{{ $message }}</div> @enderror
                    </div>

                    <hr class="mb-6">
                    <button class="bg-blue-500 hover:bg-blue-400 border border-blue-600 text-white py-3 px-4 rounded inline-block float-right" type="submit">@if(isset($link)) Save @else Create @endif</button>

                    <a href="{{(isset($link) ? route('links.show',$link) : route('links.index'))}}" class="float-right py-3 mx-4 text-gray-700">Cancel</a>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/links/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mx-auto">
        @if (session('status'))
            <div class="text-sm border border-t-8 rounded text-green-700 border-green-600 bg-green-100 px-3 py-4 mb-4" role="alert">
                {{ session('status') }}
            </div>
        @endif

        <div class="w-full block float-left relative">
           <div class="absolute w-full flex justify-between">
                <h1 class="font-medium text-gray-500 pt-4">
                    All Links
                </h1>
                <a class="bg-blue-500 hover:bg-blue-400 text-white border border-blue-600 inline-block py-4 px-5 rounded" href="{{route('links.create')}}">New Link</a>
            </div>
            <table class="bg-white border rounded shadow-md py-6 mt-16 w-full">
                <tr class="bg-gray-100 border-b-2">
                    <th class="px-6 py-4 uppercase text-sm text-gray-500 text-left">Name</th>
                    <th class="uppercase text-sm text-gray-500 text-left">Status</th>
                    <th class="px-6 py-4 uppercase text-sm text-gray-500 text-left">Recieved</th>
                    <th class="px-6 py-4 uppercase text-sm text-gray-500 text-center">Participants</th>
                    <th class=""></th>
                </tr>

            @foreach($links as $link)
                <tr class="border-b">
                    <td class="px-6 py-6"><a class="" href="{{route('links.show',$link)}}">{{$link->title}}</a></td>
                    <td class=""><span class="py-2 px-3 rounded text-green-700 text-sm font-bold bg-green-200">Open</span></td>
                    <td class="px-6 py-6 font-bold">$ {{$link->raised}}</td>
                    <td class="px-6 py-6 font-bold text-center">{{$link->paidCustomers->count()}}</td>
                    <td class="text-right pr-2">
                        <a href="{{route('links.show',$link)}}" class="bg-gray-200 hover:bg-gray-100 border border-gray-400 inline-block py-3 px-4 rounded text-gray-800">Show</a>
                    </td>
                </tr>
            @endforeach
            </table>
        </div>
    </div>
@endsection

resources/views/admin/links/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mx-auto px-4 ">
        @if (session('status'))
            <div class="text-sm border rounded text-green-700 border-green-600 bg-green-100 px-3 py-4 mb-4" role="alert">
                {{ session('status') }}
            </div>
        @endif
            @if(auth()->user()->level > 2)
                <div class="w-full flex justify-center items-start space-x-2 mb-4">
                    <div class="flex space-x-2">
                        <a class="bg-gray-200 hover:bg-gray-100 border border-gray-400 inline-block py-4 px-5 rounded text-gray-800 mr-2" href="{{route('links.edit',$link)}}">Edit</a>
                        <a class="bg-gray-200 hover:bg-gray-100 border border-gray-400 inline-block py-4 px-5 rounded text-gray-800 mr-2" href="{{route('links.export',$link)}}">Transactions</a>
                        @if($link->hasProducts())<a class="bg-gray-200 hover:bg-gray-100 border border-gray-400 inline-block py-4 px-5 rounded text-gray-800" href="{{route('links.products.export',$link)}}">Product Export</a>@endif
                    </div>
                    <div class="flex ml-auto">
                        <form method="POST" action="{{route('links.destroy',$link)}}">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="ml-auto bg-red-200 hover:bg-red-100 border border-red-400 inline-block py-4 px-5 rounded text-red-800">Delete</button>
                        </form>
                        <a class="bg-gray-200 hover:bg-gray-100 border border-gray-400 inline-block py-4 px-5 rounded text-gray-800 ml-2" href="{{route('links.dashboard',$link)}}">Live status</a>
                    </div>
                </div>
            @endif
        <div class="w-full mb-6 mx-auto md:p-0 lg:w-3/4 xl:w-2/3 block float-left relative">
            <div class="flex flex-col break-words bg-white border rounded shadow-md py-6">
                <h1 class="px-6 text-xl mb-6 text-center">Link for <b>{{$link->title}}</b></h1>
                <div class="mb-6 px-6">
                    <span class="font-medium w-full block mb-2">Shareable link</span>
                    <div class="flex mt-2">
                        <div class="w-full px-4 py-4 border border-size-1 border-gray-400 bg-yellow-100 rounded text-xl text-gray-800 shadow-inner truncate">
                            <a href="{{route('transaction.create', $link->code)}}">{{route('transaction.create', $link->code)}}</a>
                        </div>
                        <a class="bg-blue-500 hover:bg-blue-400 text-white border border-blue-600 inline-block ml-2 py-4 px-6 text-xl rounded" href="{{route('transaction.create', $link->code)}}" target="_blank">Open</a>
                    </div>
                </div>
                <div class="overflow-x-auto w-full">
                    <table class="mb-4 w-full">
                        <tr class="bg-gray-100 border-b-2 border-t-2">
                            @if(auth()->user()->level > 2)
                            <th class="px-6 py-3 uppercase text-sm text-gray-500 text-left" width="15%">Amount</th>
                            @endif
                            <th class="px-6 py-3 uppercase text-sm text-gray-500 text-left">Name</th>
                                @if(auth()->user()->level > 3)
                            <th class="px-0 py-3 uppercase text-sm text-gray-500 text-left" >Description</th>
                                @endif
                            @if($link->gateways->count() > 1)
                                <th class="px-6 py-3 uppercase text-sm text-gray-500 text-left">Account</th>
                            @endif
                            <th class="px-6 py-3 uppercase text-sm text-gray-500 text-right">Date</th>
                            <th></th>
                        </tr>
                    @forelse($transactions as $transaction)
                        <tr class="border-b">
                            @if(auth()->user()->level > 2)
                            <td class="px-6 py-4 font-bold">${{number_format($transaction->amount,2,'.',',')}}</td>
                            @endif
                            <td class="px-6 py-4 text-green-600">{{($transaction->customer->name ?? '' )}}</td>
                            @if(auth()->user()->level > 3)
                            <td class="px-0 py-4">
                                {{ $transaction->description }}
                            </td>
                            @endif
                            @if($link->gateways->count() > 1)
                                <td class="px-6 py-4">{{($transaction->gateway->name ?? '' )}}</td>
                            @endif
                            <td class="px-6 py-4 text-right text-gray-600" title="{{$transaction->updated_at->timezone('America/Los_Angeles')->diffForHumans()}}">{{$transaction->updated_at->timezone('America/Los_Angeles')->format('d M H:i')}}</td>
                            <td>
                                <a href="{{route('transactions.status.toggle', $transaction)}}" class="px-2 py-1">
                                    @if($transaction->imported)
                                        ✅
                                    @else
                                        🚫
                                    @endif
                                </a>
                            </td>
                        </tr>
                    @empty
                        <tr><td colspan="5" class="py-4 with-full text-center text-gray-500">No transactions have been made yet</td></tr>
                    @endforelse
                    </table>
                </div>
            </div>
        </div>
        <div class="w-full mb-6 mx-auto md:p-0 lg:pl-4 lg:w-1/4 xl:w-1/3 block float-left">
            <div class="bg-white border rounded shadow-md p-4 mb-4">
                <h2 class="text-xl text-gray-600 mb-4 text-center">Total</h2>
                <div class="flex">
                    @include('admin.partials.infoblock',['data' => ['Recieved' => "$". $link->raised, 'Transactions' => $link->transactions()->paid()->count()]])
                </div>
            </div>
            @if($link->gateways->count() > 1)
            <div class="bg-white border rounded shadow-md p-4 mb-4">
                @foreach($link->gateways as $gateway)
                    <span class="block font-medium w-full block mb-2 text-center text-gray-600">{{$gateway->name}}</span>
                    <div class="flex w-full pt-4 pb-8 last:pb-4 mb-4 last:mb-0 border-b last:border-b-0">
                        @include('admin.partials.infoblock',['data' => ['Recieved' => "$". $link->raisedForGateway($gateway), 'Transactions' => $link->participantsForGateway($gateway)->count() ]])
                    </div>
                @endforeach
            </div>
            @endif
            @if($link->hasProducts())
            <div class="bg-white border rounded shadow-md p-4 mb-4">
                <h2 class="text-xl text-gray-600 mb-4 text-center">Products</h2>
                @foreach($link->products()->where('multiplier','>',0)->orderBy('products.order')->get() as $product)
                <div class="flex flex-wrap border-b last:border-b-0 py-2">
                    <a href="{{route('product.pick',$product)}}" class="block font-medium w-full block text-center text-gray-600">{{$product->name}}</a>
                    <div class="flex w-full pt-4 pb-2  ">
                        @include('admin.partials.infoblock',['data' => ['Recieved' => "$". $product->raised(),'Sold' => $product->tickets()]])
                    </div>
                </div>
                @endforeach
            </div>
            @endif
            @if($link->hasTips())
                <div class="bg-white border rounded shadow-md p-4 mb-4">
                    <h2 class="text-xl text-gray-600 mb-4 text-center">Donations</h2>
                    <div class="flex w-full pt-4 pb-2  ">
                        @include('admin.partials.infoblock',['data' => ['Total' => "$". $link->raisedDonations()]])
                    </div>
                </div>
            @endif
        </div>
    </div>
@endsection