routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('auth', 'Auth\SsoController@handleProviderCallback');
Route::post('logout', 'Auth\SsoController@logout')->name('logout');

Route::redirect('/', '/links');

Route::group(['middleware' => 'auth'], function(){
    Route::resource('links', 'LinkController');
    Route::resource('gateways', 'GatewayController');

    Route::get('transactions', 'TransactionController@index')->name('transactions.index');
    Route::get('transactions/export', 'TransactionController@export')->name('transactions.export');

    Route::get('links/{link}/export', 'LinkController@export')->name('links.export');
    Route::get('links/{link}/products/export', 'LinkController@exportProducts')->name('links.products.export');
    Route::get('links/{link}/dashboard', 'LinkController@dashboard')->name('links.dashboard');

    Route::get('/products/{product}/pick', 'ProductController@pick')->name('product.pick');

    Route::get('/transactions/{transaction}/status/toggle','TransactionStatusController')->name('transactions.status.toggle');
});

Route::group(['middleware' => ['web','isCustomer']], function(){
    // public link to start a transaction
    Route::get('{link}', 'TransactionController@create')->name('transaction.create');
    Route::post('{link}', 'TransactionController@store')->name('transaction.store');
    Route::get('{link}/history', 'TransactionController@history')->name('transaction.history');

    // payment page for stripe payments
    Route::get('pay/{transaction}', 'PaymentController@create')->name('payment.create');
    Route::post('pay/{transaction}', 'PaymentController@charge')->name('payment.charge');
});


// error link
Route::get('t/{transaction}/error', 'TransactionController@error')->name('transaction.error');
// after payment return link
Route::get('t/{transaction}','TransactionController@show')->name('payment-return-url');

// webhook
Route::post('t/{provider}','TransactionController@update')->name('webhook-url');

resources/views/admin/partials/infoblock.blade.php
@foreach($data as $key => $value )
    <div class="w-full text-center xl:even:border-l border-0 pt-3 xl:pt-0">
        <h2 class="text-3xl font-medium text-gray-700 pb-2">{{ $value }}</h2>
        <span class="w-full text-gray-500">{{$key}}</span>
    </div>
@endforeach

resources/views/admin/partials/nav.blade.php
<nav class="bg-blue-900 shadow mb-3 py-6">
    <div class="container mx-auto px-4">
        <div class="flex items-center justify-center">
            <div class="mr-6">
                <a href="{{ route('links.index') }}" class="text-lg font-semibold text-gray-100 no-underline">
                    {{ config('app.name', 'Laravel') }}
                </a>
            </div>
            @auth
            <div class="flex-1 ">
                <a href="{{ route('links.index') }}" class="block float-left px-6 text-gray-500 hover:text-white">Links</a>
                <a  href="{{ route('transactions.index') }}" class="block float-left px-6 text-gray-500 hover:text-white">Transactions</a>
                <a  href="{{ route('gateways.index') }}" class="block float-left px-6 text-gray-500 hover:text-white">Integrations</a>
            </div>
            @endauth
            <div class="flex-1 text-right">
                @guest
                    <a class="no-underline hover:underline text-gray-300 text-sm p-3" href="{{ route('login') }}">{{ __('Login') }}</a>
                @else
                    <span class="text-gray-300 text-sm pr-4">{{ Auth::user()->name }}</span>

                    <a href="{{ route('logout') }}"
                       class="no-underline hover:underline text-gray-300 text-sm p-3"
                       onclick="event.preventDefault();
                            document.getElementById('logout-form').submit();">{{ __('Logout') }}</a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="hidden">
                        {{ csrf_field() }}
                    </form>
                @endguest
            </div>
        </div>
    </div>
</nav>